name: soundsee
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0

  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  lottie: ^2.7.0
  hexcolor: ^3.0.1
  navigator: ^1.1.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  snackbar: ^1.0.2
  cloud_firestore: 4.14.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/soundsee_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  android: true
  color: "#ffffff"
  image: lib/assets/images/soundsee_icon.png


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - lib/assets/images/Google.png
     - lib/assets/images/snap.json
     - lib/assets/images/update_profile.json
     - lib/assets/images/soundsee_icon.png
     - lib/assets/images/login.json
     - lib/assets/images/signup.json
     - lib/assets/images/forgot_password.json


  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: fonts/Ubuntu-Italic.ttf
          weight: 400
        - asset: fonts/Ubuntu-Bold.ttf
          weight: 700
